/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bicicletaria.gui;

import bicicletaria.dao.ClienteJpaController;
import bicicletaria.dao.exceptions.NonexistentEntityException;
import bicicletaria.dao.exceptions.PreexistingEntityException;
import bicicletaria.modelo.Cliente;
import bicicletaria.modelo.Usuario;
import bicicletaria.negocio.ControladorCliente;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author George
 */
public class JanelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastroCliente
     */
    public static EntityManagerFactory fabricabic = Persistence.createEntityManagerFactory("BicicletariaPU");  
    private static Cliente cliente = new Cliente();
    private static ClienteJpaController dao = new ClienteJpaController(fabricabic);
    private static ControladorCliente controladorCliente = new ControladorCliente();
    List<Cliente> cli = new ArrayList<Cliente>();
    
    public JanelaCadastroCliente() {
        initComponents();
        listarCliente();
        configurarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainelMenu = new javax.swing.JPanel();
        jInserir = new javax.swing.JButton();
        jEditar = new javax.swing.JButton();
        jExcluir = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jPDadosPessoais = new javax.swing.JPanel();
        jLNome = new javax.swing.JLabel();
        jLEndereco = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        jLCidade = new javax.swing.JLabel();
        jLCep = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLTelefone = new javax.swing.JLabel();
        jLCelular = new javax.swing.JLabel();
        jLCPF = new javax.swing.JLabel();
        jLEmail = new javax.swing.JLabel();
        jLData = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jEndereco = new javax.swing.JTextField();
        jBairro = new javax.swing.JTextField();
        jCidade = new javax.swing.JTextField();
        jCelular = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter celular = new javax.swing.text.MaskFormatter("(##)####-####");
            jCelular = new javax.swing.JFormattedTextField(celular);
        }
        catch (Exception e) {
        }
        jTelefone = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("(##)####-####");
            jTelefone = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e) {
        }
        jCPF = new javax.swing.JTextField();
        jData = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            jData = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e) {
        }
        jCep = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jCEstado = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPainelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bicicletaria/imagens/Ok.png"))); // NOI18N
        jInserir.setText("Inserir");
        jInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInserirActionPerformed(evt);
            }
        });

        jEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bicicletaria/imagens/edit.png"))); // NOI18N
        jEditar.setText("Editar");
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });

        jExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bicicletaria/imagens/del.png"))); // NOI18N
        jExcluir.setText("Excluir");
        jExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcluirActionPerformed(evt);
            }
        });

        jCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bicicletaria/imagens/canc.png"))); // NOI18N
        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPainelMenuLayout = new javax.swing.GroupLayout(jPainelMenu);
        jPainelMenu.setLayout(jPainelMenuLayout);
        jPainelMenuLayout.setHorizontalGroup(
            jPainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPainelMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCancelar, jEditar, jExcluir, jInserir});

        jPainelMenuLayout.setVerticalGroup(
            jPainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPainelMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jCancelar, jEditar, jExcluir, jInserir});

        jPDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLNome.setText("Nome *");

        jLEndereco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLEndereco.setText("Endereço");

        jLBairro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLBairro.setText("Bairro");

        jLCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLCidade.setText("Cidade");

        jLCep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLCep.setText("CEP");

        jLEstado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLEstado.setText("Estado");

        jLTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLTelefone.setText("Telefone *");

        jLCelular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLCelular.setText("Celular");

        jLCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLCPF.setText("CPF *");

        jLEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLEmail.setText("E-mail");

        jLData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLData.setText("Data de Nascimento");

        jNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeActionPerformed(evt);
            }
        });

        try {
            javax.swing.text.MaskFormatter cpf_mask = new javax.swing.text.MaskFormatter("###.###.###-##");
            jCPF = new javax.swing.JFormattedTextField(cpf_mask);
        }
        catch (Exception e) {
        }
        jCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCPFKeyTyped(evt);
            }
        });

        jCEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceara", "Distrito Federal", "Espirito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Para", "Paraiba", "Parana", "Pernambuco", "Piaui", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));

        javax.swing.GroupLayout jPDadosPessoaisLayout = new javax.swing.GroupLayout(jPDadosPessoais);
        jPDadosPessoais.setLayout(jPDadosPessoaisLayout);
        jPDadosPessoaisLayout.setHorizontalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNome, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                        .addGap(222, 222, 222))
                                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(89, 89, 89)
                                        .addComponent(jLCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(87, 87, 87)))
                                .addGap(4, 4, 4))
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jCPF)
                                .addGap(141, 141, 141))
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(223, 223, 223)))
                                .addGap(17, 17, 17))
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCelular)
                                .addGap(16, 16, 16))
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(243, 243, 243))
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(236, 236, 236))
                            .addComponent(jEmail)
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(jLCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(248, 248, 248)))
                        .addGap(6, 6, 6)
                        .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCep)
                            .addComponent(jBairro)
                            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLData, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))
                                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(82, 82, 82))
                                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLCep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(96, 96, 96))
                                    .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(jLEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(78, 78, 78))
                                    .addComponent(jData))
                                .addGap(50, 50, 50)))))
                .addContainerGap())
        );
        jPDadosPessoaisLayout.setVerticalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEndereco)
                    .addComponent(jBairro))
                .addGap(18, 18, 18)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCep)
                    .addComponent(jCidade))
                .addGap(8, 8, 8)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefone)
                    .addComponent(jCelular)
                    .addComponent(jCEstado))
                .addGap(18, 18, 18)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jData)
                    .addComponent(jCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEmail)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Bairro", "Cidade", "CEP", "Telefone", "Celular", "Estado", "CPF", "Data Nascimento", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(582, 582, 582)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPainelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPainelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNomeActionPerformed

    private void jCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCPFKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
             evt.consume();
        }
    }//GEN-LAST:event_jCPFKeyTyped

    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarActionPerformed

    private void jInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInserirActionPerformed
        cliente.setNome(jNome.getText());
        cliente.setCpf(jCPF.getText());
        cliente.setDatanascimento(jData.getText());
        cliente.setBairro(jBairro.getText());
        cliente.setEndereco(jEndereco.getText());
        cliente.setCep(jCep.getText());
        cliente.setTelefone(jTelefone.getText());
        cliente.setCelular(jCelular.getText());
        cliente.setEmail(jEmail.getText());
        cliente.setCidade(jCidade.getText());
        cliente.setEstado(jCEstado.getSelectedItem().toString());
        controladorCliente.inserir(cliente);
        JOptionPane.showMessageDialog(this, controladorCliente.getMensagem());
        listarCliente();
        limparCampos();
    }//GEN-LAST:event_jInserirActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaMouseClicked

    private void jExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcluirActionPerformed
        String cpf = jCPF.getText();
        if(JOptionPane.showConfirmDialog(this, "Deseja excluir esse registro?") == 0){
            try {
                
                    dao.destroy(cpf);

            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JanelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        limparCampos();
        listarCliente();
    }//GEN-LAST:event_jExcluirActionPerformed

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
            
            Cliente cli = new Cliente();
            cli.setNome(jNome.getText());//.toLowerCase());
            cli.setCpf(jCPF.getText());
            cli.setDatanascimento(jData.getText());
            cli.setBairro(jBairro.getText());
            cli.setEndereco(jEndereco.getText());
            cli.setCep(jCep.getText());
            cli.setTelefone(jTelefone.getText());
            cli.setCelular(jCelular.getText());
            cli.setEmail(jEmail.getText());
            cli.setCidade(jCidade.getText());
            cli.setEstado(jCEstado.getSelectedItem().toString());
         
            try {
                dao.edit(cli);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(JanelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(JanelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            limparCampos();
            listarCliente(); 
    }//GEN-LAST:event_jEditarActionPerformed
    
    

      private void configurarEventos(){
            tabela.addMouseListener(new MouseAdapter() {
                @Override
                    public void mouseClicked(MouseEvent e){
                        //configurarTabela();    
                        configurarEventosTabela();
                        
                    }
            });
    }
      
    public void configurarEventosTabela(){    
        
            int indice = tabela.getSelectedRow();
            
            if(indice >= cli.size()){  
                limparCampos();
            }
            
            else{
                    //Ideia, passar clientes para um array list e passalos para o textField
                    jNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
                    jEndereco.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
                    jBairro.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
                    jCidade.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
                    jCep.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
                    jTelefone.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
                    jCelular.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
                    jCEstado.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
                    jCPF.setText(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());
                    jData.setText(tabela.getValueAt(tabela.getSelectedRow(), 9).toString()); 
                    jEmail.setText(tabela.getValueAt(tabela.getSelectedRow(), 10).toString());
                    
                
                
            }

    }
    
    public void limparCampos(){
        
                         jNome.setText("");
                         jCPF.setText("");
                         jData.setText("");
                         jBairro.setText("");
                         jEndereco.setText("");
                         jCep.setText("");
                         jTelefone.setText("");
                         jCelular.setText("");
                         jEmail.setText("");
                         jCidade.setText("");
                         jCEstado.setSelectedItem("");
    }        
     public void listarCliente(){
            criarTabela();
            
            cli = dao.findClienteEntities();
            //String[] campos = new String [] {null, null, null, null, null};
            for(int i = 0; i < cli.size(); i++){ //usu.size() verifica o tamanho List  
               tabela.setValueAt(cli.get(i).getNome(), i, 0); 
               tabela.setValueAt(cli.get(i).getEndereco(), i, 1); 
               tabela.setValueAt(cli.get(i).getBairro(), i, 2);  
               tabela.setValueAt(cli.get(i).getCidade(), i, 3);
               tabela.setValueAt(cli.get(i).getCep(), i, 4);
               tabela.setValueAt(cli.get(i).getTelefone(), i, 5);
               tabela.setValueAt(cli.get(i).getCelular(), i, 6);
               tabela.setValueAt(cli.get(i).getEstado(), i, 7);
               tabela.setValueAt(cli.get(i).getCpf(), i, 8);
               tabela.setValueAt(cli.get(i).getDatanascimento(), i, 9);
               tabela.setValueAt(cli.get(i).getEmail(), i, 10);
               

            }        
        }
    
     public void criarTabela(){
        tabela.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                   {null, null, null, null, null, null, null, null, null, null, null},
                   {null, null, null, null, null, null, null, null, null, null, null},
                   {null, null, null, null, null, null, null, null, null, null, null},
                   {null, null, null, null, null, null, null, null, null, null, null}
               },
               new String [] {
                   "Nome", "Endereço", "Bairro", "Cidade", "CEP", "Telefone", "Celular", "Estado", "CPF", "Data Nascimento", "Email"
               }
           ) {
               Class[] types = new Class [] {
                   java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
               };
               boolean[] canEdit = new boolean [] {
                   false, false, false, false, false, false, false, false, false, false, false
               };

               public Class getColumnClass(int columnIndex) {
                   return types [columnIndex];
               }

               public boolean isCellEditable(int rowIndex, int columnIndex) {
                   return canEdit [columnIndex];
               }
           });
     }
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBairro;
    private javax.swing.JComboBox jCEstado;
    private javax.swing.JTextField jCPF;
    private javax.swing.JButton jCancelar;
    private javax.swing.JTextField jCelular;
    private javax.swing.JTextField jCep;
    private javax.swing.JTextField jCidade;
    private javax.swing.JTextField jData;
    private javax.swing.JButton jEditar;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jEndereco;
    private javax.swing.JButton jExcluir;
    private javax.swing.JButton jInserir;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLCelular;
    private javax.swing.JLabel jLCep;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JTextField jNome;
    private javax.swing.JPanel jPDadosPessoais;
    private javax.swing.JPanel jPainelMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTelefone;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
